import Head from 'next/head'
import { Montserrat, Yantramanav } from '@next/font/google'
import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { library } from '@fortawesome/fontawesome-svg-core';
import {faComment, faHouse, faUserGroup, faInfinity} from '@fortawesome/free-solid-svg-icons';

const yantramanav = Yantramanav({
  weight: "400",
  subsets: ["latin"]
})

export default function Chat() {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
      <main className=''>
        <div className='h-screen' >
            <div className='wh-chat flex'>
              <div className='p-8 navbar-ct font-montserrat'>
                  <h1 className='text-3xl text-center' >Sirkelin.</h1> 
                  <div className='mt-12 grid text-center gap-10 text-xl'>
                    <button className='flex group gap-4 hover:bg-purple-900 hover:ring-pbg-purple-900 rounded-xl p-2'><FontAwesomeIcon className='self-center group-hover:stroke-white ' icon = {faComment}/><h1 style={yantramanav.style} className='ml-4 font-yantramanav'>  messages</h1></button>
                    <button className='flex group gap-4 hover:bg-purple-900 hover:ring-pbg-purple-900 rounded-xl p-2'><FontAwesomeIcon className='self-center group-hover:stroke-white ' icon={faInfinity} /><h2 style={yantramanav.style} className=' ml-3 font-yantramanav'> circle</h2></button>
                    <button className='flex group gap-4 hover:bg-purple-900 hover:ring-pbg-purple-900 rounded-xl p-2'><FontAwesomeIcon className='self-center group-hover:stroke-white ' icon={faUserGroup} /><h3 style={yantramanav.style} className=' ml-3 font-yantramanav'> friend list</h3></button>
                    <button className='flex group gap-4 hover:bg-purple-900 hover:ring-pbg-purple-900 rounded-xl p-2'><FontAwesomeIcon className='self-center group-hover:stroke-white ' icon={faHouse} /><h4 style={yantramanav.style} className=' ml-3 font-yantramanav'> explore</h4></button>
                  </div>
              </div>
            </div>
        </div>
      </main>

    </>
  )
}

